### ISSUE TITLE
Numpy Error

### ISSUE THREAD

**Issue by chaojian-zhang** [prman-pixar/RenderManForBlender#681]
Both RfB 25.0 and 25.1 has issue with Blender 3.5 (and Blender 3.6):

```
Export failed: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
```

To reproduce:

1. Download Blender 3.5 for Windows: https://www.blender.org/download/release/Blender3.5/blender-3.5.1-windows-x64.zip/
2. Download RfB Plugin 25.1 https://github.com/prman-pixar/RenderManForBlender/releases/tag/v_25.1
3. Install Plugin
4. Try to render default cube scene

![image](https://github.com/prman-pixar/RenderManForBlender/assets/7077098/66ddd96c-bd9f-4a47-8d27-0c38fc90f1c9)

FYI, Blender 3.5 comes with numpy at version '1.24.2'

![image](https://github.com/prman-pixar/RenderManForBlender/assets/7077098/8b8a73da-63c7-468d-92cc-6498bd5ca897)

I am surprised no one mentions it.

I can confirm that the same plugin (RfB 25.1) works with Blender version 3.3.7.

See attachment for system info: [system-info.txt](https://github.com/prman-pixar/RenderManForBlender/files/11776832/system-info.txt)

**Comment by prman-pixar** [comment]
@chaojian-zhang I just committed a fix for this in the dev branch. Can you see if it fixes for you?

**Comment by chaojian-zhang** [comment]
Thanks for the timely fix! I can verify the dev branch as of https://github.com/prman-pixar/RenderManForBlender/commit/c07de446815645b83ac003c0271197bbfc4bff3c works without problem now!
